#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/../vendor/autoload.php';

use Minicli\App;

$app = new App([
        'debug' => false,
        'app_path' => __DIR__ . '/app/Command',
        'theme' => 'App\CustomTheme\Theme\Blue'
]);

$app->setSignature("Minicli DEMOS: Custom Theme\n./minicli styles\n");
$app->runCommand($argv);
